/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainWindow (void);
GtkWidget* create_aboutWindow (void);
GtkWidget* create_authorWindow (void);
GtkWidget* create_fileselection (void);
