/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define TITLE "GBabbler " VERSION

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mainWindow (void)
{
  GtkWidget *mainWindow;
  GtkWidget *vbox1;
  GtkWidget *menubar;
  GtkWidget *file;
  GtkWidget *file_menu;
  GtkWidget *new;
  GtkWidget *image202;
  GtkWidget *open;
  GtkWidget *image203;
  GtkWidget *save;
  GtkWidget *image204;
  GtkWidget *save_as;
  GtkWidget *image205;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit;
  GtkWidget *image206;
  GtkWidget *babble;
  GtkWidget *babble_menu;
  GtkWidget *find_words;
  GtkWidget *image207;
  GtkWidget *help;
  GtkWidget *help_menu;
  GtkWidget *about;
  GtkWidget *notebook;
  GtkWidget *hbox1;
  GtkWidget *vbox2;
  GtkWidget *babbleTitleLabel;
  GtkWidget *frame1;
  GtkWidget *vbox3;
  GtkWidget *vbox4;
  GtkWidget *hbox2;
  GtkWidget *wordNblabel;
  GtkObject *wordNumbers_adj;
  GtkWidget *wordNumbers;
  GtkWidget *wordProgress;
  GtkWidget *vbox5;
  GtkWidget *lengthCheck;
  GtkWidget *alignment1;
  GtkWidget *hbox4;
  GtkWidget *image116;
  GtkWidget *label6;
  GtkWidget *hbox3;
  GtkWidget *lengthLabel;
  GtkObject *wordLength_adj;
  GtkWidget *wordLength;
  GtkWidget *reservedLabel;
  GtkWidget *babbleParamsLabel;
  GtkWidget *letsgo;
  GtkWidget *scrolledwindow3;
  GtkWidget *viewport1;
  GtkWidget *wordView;
  GtkWidget *babbleNoteLabel;
  GtkWidget *vbox9;
  GtkWidget *vbox10;
  GtkWidget *vbox11;
  GtkWidget *table1;
  GtkWidget *themeNameLabel;
  GtkWidget *themeFilenameLabel;
  GtkWidget *themeWeightLabel;
  GtkWidget *themeNameEntry;
  GtkObject *themeWeightSpin_adj;
  GtkWidget *themeWeightSpin;
  GtkWidget *hbox22;
  GtkWidget *themeFilenameEntry;
  GtkWidget *themeFilenameButton;
  GtkWidget *hbuttonbox2;
  GtkWidget *themeAddButton;
  GtkWidget *alignment13;
  GtkWidget *hbox25;
  GtkWidget *image194;
  GtkWidget *label31;
  GtkWidget *themeRemoveButton;
  GtkWidget *alignment12;
  GtkWidget *hbox24;
  GtkWidget *image193;
  GtkWidget *label30;
  GtkWidget *themeModify;
  GtkWidget *alignment15;
  GtkWidget *hbox27;
  GtkWidget *image196;
  GtkWidget *label36;
  GtkWidget *scrolledwindow5;
  GtkWidget *treeview;
  GtkWidget *themeNoteLabel;
  GtkWidget *statusbar;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  mainWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (mainWindow, "mainWindow");
  gtk_widget_set_size_request (mainWindow, 500, 400);
  gtk_window_set_title (GTK_WINDOW (mainWindow), _("GBabbler"));
  gtk_window_set_position (GTK_WINDOW (mainWindow), GTK_WIN_POS_CENTER);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainWindow), vbox1);

  menubar = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar, "menubar");
  gtk_widget_show (menubar);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar, FALSE, FALSE, 0);

  file = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_set_name (file, "file");
  gtk_widget_show (file);
  gtk_container_add (GTK_CONTAINER (menubar), file);

  file_menu = gtk_menu_new ();
  gtk_widget_set_name (file_menu, "file_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file), file_menu);

  new = gtk_image_menu_item_new_with_mnemonic (_("_New"));
  gtk_widget_set_name (new, "new");
  gtk_widget_show (new);
  gtk_container_add (GTK_CONTAINER (file_menu), new);

  image202 = gtk_image_new_from_stock ("gtk-new", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image202, "image202");
  gtk_widget_show (image202);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (new), image202);

  open = gtk_image_menu_item_new_with_mnemonic (_("_Open"));
  gtk_widget_set_name (open, "open");
  gtk_widget_show (open);
  gtk_container_add (GTK_CONTAINER (file_menu), open);

  image203 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image203, "image203");
  gtk_widget_show (image203);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (open), image203);

  save = gtk_image_menu_item_new_with_mnemonic (_("_Save"));
  gtk_widget_set_name (save, "save");
  gtk_widget_show (save);
  gtk_container_add (GTK_CONTAINER (file_menu), save);

  image204 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image204, "image204");
  gtk_widget_show (image204);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (save), image204);

  save_as = gtk_image_menu_item_new_with_mnemonic (_("Save _As"));
  gtk_widget_set_name (save_as, "save_as");
  gtk_widget_show (save_as);
  gtk_container_add (GTK_CONTAINER (file_menu), save_as);

  image205 = gtk_image_new_from_stock ("gtk-save-as", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image205, "image205");
  gtk_widget_show (image205);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (save_as), image205);

  separatormenuitem1 = gtk_menu_item_new ();
  gtk_widget_set_name (separatormenuitem1, "separatormenuitem1");
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (file_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit = gtk_image_menu_item_new_with_mnemonic (_("_Quit"));
  gtk_widget_set_name (quit, "quit");
  gtk_widget_show (quit);
  gtk_container_add (GTK_CONTAINER (file_menu), quit);
  gtk_widget_add_accelerator (quit, "activate", accel_group,
                              GDK_Q, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  image206 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image206, "image206");
  gtk_widget_show (image206);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (quit), image206);

  babble = gtk_menu_item_new_with_mnemonic (_("_Babble"));
  gtk_widget_set_name (babble, "babble");
  gtk_widget_show (babble);
  gtk_container_add (GTK_CONTAINER (menubar), babble);

  babble_menu = gtk_menu_new ();
  gtk_widget_set_name (babble_menu, "babble_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (babble), babble_menu);

  find_words = gtk_image_menu_item_new_with_mnemonic (_("_Find words"));
  gtk_widget_set_name (find_words, "find_words");
  gtk_widget_show (find_words);
  gtk_container_add (GTK_CONTAINER (babble_menu), find_words);

  image207 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_MENU);
  gtk_widget_set_name (image207, "image207");
  gtk_widget_show (image207);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (find_words), image207);

  help = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_set_name (help, "help");
  gtk_widget_show (help);
  gtk_container_add (GTK_CONTAINER (menubar), help);

  help_menu = gtk_menu_new ();
  gtk_widget_set_name (help_menu, "help_menu");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help), help_menu);

  about = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_set_name (about, "about");
  gtk_widget_show (about);
  gtk_container_add (GTK_CONTAINER (help_menu), about);

  notebook = gtk_notebook_new ();
  gtk_widget_set_name (notebook, "notebook");
  gtk_widget_show (notebook);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (notebook), hbox1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (hbox1), vbox2, TRUE, TRUE, 0);

  babbleTitleLabel = gtk_label_new (_("Babbler Control"));
  gtk_widget_set_name (babbleTitleLabel, "babbleTitleLabel");
  gtk_widget_show (babbleTitleLabel);
  gtk_box_pack_start (GTK_BOX (vbox2), babbleTitleLabel, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (babbleTitleLabel), GTK_JUSTIFY_LEFT);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame1, "frame1");
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox2), frame1, TRUE, TRUE, 0);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (frame1), vbox3);

  vbox4 = gtk_vbox_new (TRUE, 0);
  gtk_widget_set_name (vbox4, "vbox4");
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (vbox3), vbox4, TRUE, TRUE, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox2, FALSE, TRUE, 0);

  wordNblabel = gtk_label_new (_("Words #"));
  gtk_widget_set_name (wordNblabel, "wordNblabel");
  gtk_widget_show (wordNblabel);
  gtk_box_pack_start (GTK_BOX (hbox2), wordNblabel, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (wordNblabel), GTK_JUSTIFY_LEFT);

  wordNumbers_adj = gtk_adjustment_new (10, 1, 1000, 1, 10, 10);
  wordNumbers = gtk_spin_button_new (GTK_ADJUSTMENT (wordNumbers_adj), 1, 0);
  gtk_widget_set_name (wordNumbers, "wordNumbers");
  gtk_widget_show (wordNumbers);
  gtk_box_pack_start (GTK_BOX (hbox2), wordNumbers, TRUE, TRUE, 0);
  gtk_spin_button_set_update_policy (GTK_SPIN_BUTTON (wordNumbers), GTK_UPDATE_IF_VALID);

  wordProgress = gtk_progress_bar_new ();
  gtk_widget_set_name (wordProgress, "wordProgress");
  gtk_widget_show (wordProgress);
  gtk_box_pack_start (GTK_BOX (vbox4), wordProgress, FALSE, FALSE, 0);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (wordProgress), _("words"));

  vbox5 = gtk_vbox_new (TRUE, 0);
  gtk_widget_set_name (vbox5, "vbox5");
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (vbox3), vbox5, TRUE, TRUE, 0);

  lengthCheck = gtk_check_button_new ();
  gtk_widget_set_name (lengthCheck, "lengthCheck");
  gtk_widget_show (lengthCheck);
  gtk_box_pack_start (GTK_BOX (vbox5), lengthCheck, FALSE, FALSE, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (lengthCheck), alignment1);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox4);

  image116 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image116, "image116");
  gtk_widget_show (image116);
  gtk_box_pack_start (GTK_BOX (hbox4), image116, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Length Limit"));
  gtk_widget_set_name (label6, "label6");
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox4), label6, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_LEFT);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox3, TRUE, TRUE, 0);

  lengthLabel = gtk_label_new (_("Length"));
  gtk_widget_set_name (lengthLabel, "lengthLabel");
  gtk_widget_show (lengthLabel);
  gtk_box_pack_start (GTK_BOX (hbox3), lengthLabel, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (lengthLabel), GTK_JUSTIFY_LEFT);

  wordLength_adj = gtk_adjustment_new (6, 3, 100, 1, 10, 10);
  wordLength = gtk_spin_button_new (GTK_ADJUSTMENT (wordLength_adj), 1, 0);
  gtk_widget_set_name (wordLength, "wordLength");
  gtk_widget_show (wordLength);
  gtk_box_pack_start (GTK_BOX (hbox3), wordLength, TRUE, TRUE, 0);
  gtk_widget_set_sensitive (wordLength, FALSE);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (wordLength), TRUE);
  gtk_spin_button_set_update_policy (GTK_SPIN_BUTTON (wordLength), GTK_UPDATE_IF_VALID);

  reservedLabel = gtk_label_new (_("reserved ;-)"));
  gtk_widget_set_name (reservedLabel, "reservedLabel");
  gtk_widget_show (reservedLabel);
  gtk_box_pack_start (GTK_BOX (vbox3), reservedLabel, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (reservedLabel), GTK_JUSTIFY_LEFT);

  babbleParamsLabel = gtk_label_new (_("Parameters"));
  gtk_widget_set_name (babbleParamsLabel, "babbleParamsLabel");
  gtk_widget_show (babbleParamsLabel);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), babbleParamsLabel);
  gtk_label_set_justify (GTK_LABEL (babbleParamsLabel), GTK_JUSTIFY_LEFT);

  letsgo = gtk_button_new_with_mnemonic (_("Let's Go !"));
  gtk_widget_set_name (letsgo, "letsgo");
  gtk_widget_show (letsgo);
  gtk_box_pack_start (GTK_BOX (vbox2), letsgo, FALSE, FALSE, 0);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow3, "scrolledwindow3");
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (hbox1), scrolledwindow3, TRUE, TRUE, 0);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (viewport1, "viewport1");
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), viewport1);

  wordView = gtk_label_new ("");
  gtk_widget_set_name (wordView, "wordView");
  gtk_widget_show (wordView);
  gtk_container_add (GTK_CONTAINER (viewport1), wordView);
  GTK_WIDGET_SET_FLAGS (wordView, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (wordView), TRUE);
  gtk_label_set_justify (GTK_LABEL (wordView), GTK_JUSTIFY_LEFT);
  gtk_label_set_selectable (GTK_LABEL (wordView), TRUE);

  babbleNoteLabel = gtk_label_new (_("Babble"));
  gtk_widget_set_name (babbleNoteLabel, "babbleNoteLabel");
  gtk_widget_show (babbleNoteLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 0), babbleNoteLabel);
  gtk_label_set_justify (GTK_LABEL (babbleNoteLabel), GTK_JUSTIFY_LEFT);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox9, "vbox9");
  gtk_widget_show (vbox9);
  gtk_container_add (GTK_CONTAINER (notebook), vbox9);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox10, "vbox10");
  gtk_widget_show (vbox10);
  gtk_box_pack_start (GTK_BOX (vbox9), vbox10, TRUE, TRUE, 0);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox11, "vbox11");
  gtk_widget_show (vbox11);
  gtk_box_pack_start (GTK_BOX (vbox10), vbox11, TRUE, TRUE, 0);

  table1 = gtk_table_new (3, 2, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox11), table1, TRUE, TRUE, 0);

  themeNameLabel = gtk_label_new (_("Name: "));
  gtk_widget_set_name (themeNameLabel, "themeNameLabel");
  gtk_widget_show (themeNameLabel);
  gtk_table_attach (GTK_TABLE (table1), themeNameLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (themeNameLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (themeNameLabel), 0, 0.5);

  themeFilenameLabel = gtk_label_new (_("Filename: "));
  gtk_widget_set_name (themeFilenameLabel, "themeFilenameLabel");
  gtk_widget_show (themeFilenameLabel);
  gtk_table_attach (GTK_TABLE (table1), themeFilenameLabel, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (themeFilenameLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (themeFilenameLabel), 0, 0.5);

  themeWeightLabel = gtk_label_new (_("Weight: "));
  gtk_widget_set_name (themeWeightLabel, "themeWeightLabel");
  gtk_widget_show (themeWeightLabel);
  gtk_table_attach (GTK_TABLE (table1), themeWeightLabel, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (themeWeightLabel), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (themeWeightLabel), 0, 0.5);

  themeNameEntry = gtk_entry_new ();
  gtk_widget_set_name (themeNameEntry, "themeNameEntry");
  gtk_widget_show (themeNameEntry);
  gtk_table_attach (GTK_TABLE (table1), themeNameEntry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  themeWeightSpin_adj = gtk_adjustment_new (50, 0, 100, 1, 10, 10);
  themeWeightSpin = gtk_spin_button_new (GTK_ADJUSTMENT (themeWeightSpin_adj), 1, 0);
  gtk_widget_set_name (themeWeightSpin, "themeWeightSpin");
  gtk_widget_show (themeWeightSpin);
  gtk_table_attach (GTK_TABLE (table1), themeWeightSpin, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbox22 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox22, "hbox22");
  gtk_widget_show (hbox22);
  gtk_table_attach (GTK_TABLE (table1), hbox22, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  themeFilenameEntry = gtk_entry_new ();
  gtk_widget_set_name (themeFilenameEntry, "themeFilenameEntry");
  gtk_widget_show (themeFilenameEntry);
  gtk_box_pack_start (GTK_BOX (hbox22), themeFilenameEntry, TRUE, TRUE, 0);

  themeFilenameButton = gtk_button_new_with_mnemonic (_("..."));
  gtk_widget_set_name (themeFilenameButton, "themeFilenameButton");
  gtk_widget_show (themeFilenameButton);
  gtk_box_pack_start (GTK_BOX (hbox22), themeFilenameButton, FALSE, FALSE, 0);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox2, "hbuttonbox2");
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox11), hbuttonbox2, TRUE, TRUE, 0);

  themeAddButton = gtk_button_new ();
  gtk_widget_set_name (themeAddButton, "themeAddButton");
  gtk_widget_show (themeAddButton);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), themeAddButton);
  GTK_WIDGET_SET_FLAGS (themeAddButton, GTK_CAN_DEFAULT);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment13, "alignment13");
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (themeAddButton), alignment13);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox25, "hbox25");
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox25);

  image194 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image194, "image194");
  gtk_widget_show (image194);
  gtk_box_pack_start (GTK_BOX (hbox25), image194, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Add"));
  gtk_widget_set_name (label31, "label31");
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox25), label31, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label31), GTK_JUSTIFY_LEFT);

  themeRemoveButton = gtk_button_new ();
  gtk_widget_set_name (themeRemoveButton, "themeRemoveButton");
  gtk_widget_show (themeRemoveButton);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), themeRemoveButton);
  GTK_WIDGET_SET_FLAGS (themeRemoveButton, GTK_CAN_DEFAULT);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment12, "alignment12");
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (themeRemoveButton), alignment12);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox24, "hbox24");
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox24);

  image193 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image193, "image193");
  gtk_widget_show (image193);
  gtk_box_pack_start (GTK_BOX (hbox24), image193, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Remove"));
  gtk_widget_set_name (label30, "label30");
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox24), label30, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label30), GTK_JUSTIFY_LEFT);

  themeModify = gtk_button_new ();
  gtk_widget_set_name (themeModify, "themeModify");
  gtk_widget_show (themeModify);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), themeModify);
  GTK_WIDGET_SET_FLAGS (themeModify, GTK_CAN_DEFAULT);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment15, "alignment15");
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (themeModify), alignment15);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox27, "hbox27");
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox27);

  image196 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image196, "image196");
  gtk_widget_show (image196);
  gtk_box_pack_start (GTK_BOX (hbox27), image196, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Modify"));
  gtk_widget_set_name (label36, "label36");
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox27), label36, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label36), GTK_JUSTIFY_LEFT);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow5, "scrolledwindow5");
  gtk_widget_show (scrolledwindow5);
  gtk_box_pack_start (GTK_BOX (vbox10), scrolledwindow5, TRUE, TRUE, 0);

  treeview = gtk_tree_view_new ();
  gtk_widget_set_name (treeview, "treeview");
  gtk_widget_show (treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), treeview);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (treeview), TRUE);

  themeNoteLabel = gtk_label_new (_("Themes"));
  gtk_widget_set_name (themeNoteLabel, "themeNoteLabel");
  gtk_widget_show (themeNoteLabel);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook), 1), themeNoteLabel);
  gtk_label_set_justify (GTK_LABEL (themeNoteLabel), GTK_JUSTIFY_LEFT);

  statusbar = gtk_statusbar_new ();
  gtk_widget_set_name (statusbar, "statusbar");
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) mainWindow, "destroy",
                    G_CALLBACK (on_mainWindow_destroy),
                    NULL);
  g_signal_connect ((gpointer) new, "activate",
                    G_CALLBACK (on_new_activate),
                    NULL);
  g_signal_connect ((gpointer) open, "activate",
                    G_CALLBACK (on_open_activate),
                    NULL);
  g_signal_connect ((gpointer) save, "activate",
                    G_CALLBACK (on_save_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as, "activate",
                    G_CALLBACK (on_save_as_activate),
                    NULL);
  g_signal_connect ((gpointer) quit, "activate",
                    G_CALLBACK (on_quit_activate),
                    NULL);
  g_signal_connect ((gpointer) find_words, "activate",
                    G_CALLBACK (on_find_words_activate),
                    NULL);
  g_signal_connect ((gpointer) about, "activate",
                    G_CALLBACK (on_about_activate),
                    NULL);
  g_signal_connect ((gpointer) wordNumbers, "value_changed",
                    G_CALLBACK (on_wordNumbers_changed),
                    NULL);
  g_signal_connect ((gpointer) lengthCheck, "toggled",
                    G_CALLBACK (on_lengthCheck_toggled),
                    NULL);
  g_signal_connect ((gpointer) wordLength, "value_changed",
                    G_CALLBACK (on_wordLength_changed),
                    NULL);
  g_signal_connect ((gpointer) letsgo, "clicked",
                    G_CALLBACK (on_find_words_activate),
                    NULL);
  g_signal_connect ((gpointer) themeNameEntry, "changed",
                    G_CALLBACK (on_themeNameEntry_changed),
                    NULL);
  g_signal_connect ((gpointer) themeWeightSpin, "value_changed",
                    G_CALLBACK (on_themeWeightSpin_value_changed),
                    NULL);
  g_signal_connect ((gpointer) themeFilenameEntry, "changed",
                    G_CALLBACK (on_themeFilenameEntry_changed),
                    NULL);
  g_signal_connect ((gpointer) themeFilenameButton, "clicked",
                    G_CALLBACK (on_themeFilenameButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) themeAddButton, "clicked",
                    G_CALLBACK (on_themeAddButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) themeRemoveButton, "clicked",
                    G_CALLBACK (on_themeRemoveButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) themeModify, "clicked",
                    G_CALLBACK (on_themeModify_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview, "cursor_changed",
                    G_CALLBACK (on_treeview_cursor_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainWindow, mainWindow, "mainWindow");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (mainWindow, menubar, "menubar");
  GLADE_HOOKUP_OBJECT (mainWindow, file, "file");
  GLADE_HOOKUP_OBJECT (mainWindow, file_menu, "file_menu");
  GLADE_HOOKUP_OBJECT (mainWindow, new, "new");
  GLADE_HOOKUP_OBJECT (mainWindow, image202, "image202");
  GLADE_HOOKUP_OBJECT (mainWindow, open, "open");
  GLADE_HOOKUP_OBJECT (mainWindow, image203, "image203");
  GLADE_HOOKUP_OBJECT (mainWindow, save, "save");
  GLADE_HOOKUP_OBJECT (mainWindow, image204, "image204");
  GLADE_HOOKUP_OBJECT (mainWindow, save_as, "save_as");
  GLADE_HOOKUP_OBJECT (mainWindow, image205, "image205");
  GLADE_HOOKUP_OBJECT (mainWindow, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (mainWindow, quit, "quit");
  GLADE_HOOKUP_OBJECT (mainWindow, image206, "image206");
  GLADE_HOOKUP_OBJECT (mainWindow, babble, "babble");
  GLADE_HOOKUP_OBJECT (mainWindow, babble_menu, "babble_menu");
  GLADE_HOOKUP_OBJECT (mainWindow, find_words, "find_words");
  GLADE_HOOKUP_OBJECT (mainWindow, image207, "image207");
  GLADE_HOOKUP_OBJECT (mainWindow, help, "help");
  GLADE_HOOKUP_OBJECT (mainWindow, help_menu, "help_menu");
  GLADE_HOOKUP_OBJECT (mainWindow, about, "about");
  GLADE_HOOKUP_OBJECT (mainWindow, notebook, "notebook");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (mainWindow, babbleTitleLabel, "babbleTitleLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (mainWindow, wordNblabel, "wordNblabel");
  GLADE_HOOKUP_OBJECT (mainWindow, wordNumbers, "wordNumbers");
  GLADE_HOOKUP_OBJECT (mainWindow, wordProgress, "wordProgress");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (mainWindow, lengthCheck, "lengthCheck");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (mainWindow, image116, "image116");
  GLADE_HOOKUP_OBJECT (mainWindow, label6, "label6");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (mainWindow, lengthLabel, "lengthLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, wordLength, "wordLength");
  GLADE_HOOKUP_OBJECT (mainWindow, reservedLabel, "reservedLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, babbleParamsLabel, "babbleParamsLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, letsgo, "letsgo");
  GLADE_HOOKUP_OBJECT (mainWindow, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (mainWindow, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (mainWindow, wordView, "wordView");
  GLADE_HOOKUP_OBJECT (mainWindow, babbleNoteLabel, "babbleNoteLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (mainWindow, table1, "table1");
  GLADE_HOOKUP_OBJECT (mainWindow, themeNameLabel, "themeNameLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, themeFilenameLabel, "themeFilenameLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, themeWeightLabel, "themeWeightLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, themeNameEntry, "themeNameEntry");
  GLADE_HOOKUP_OBJECT (mainWindow, themeWeightSpin, "themeWeightSpin");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (mainWindow, themeFilenameEntry, "themeFilenameEntry");
  GLADE_HOOKUP_OBJECT (mainWindow, themeFilenameButton, "themeFilenameButton");
  GLADE_HOOKUP_OBJECT (mainWindow, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (mainWindow, themeAddButton, "themeAddButton");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (mainWindow, image194, "image194");
  GLADE_HOOKUP_OBJECT (mainWindow, label31, "label31");
  GLADE_HOOKUP_OBJECT (mainWindow, themeRemoveButton, "themeRemoveButton");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (mainWindow, image193, "image193");
  GLADE_HOOKUP_OBJECT (mainWindow, label30, "label30");
  GLADE_HOOKUP_OBJECT (mainWindow, themeModify, "themeModify");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (mainWindow, image196, "image196");
  GLADE_HOOKUP_OBJECT (mainWindow, label36, "label36");
  GLADE_HOOKUP_OBJECT (mainWindow, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (mainWindow, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (mainWindow, themeNoteLabel, "themeNoteLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, statusbar, "statusbar");

  gtk_window_add_accel_group (GTK_WINDOW (mainWindow), accel_group);

  return mainWindow;
}

GtkWidget*
create_aboutWindow (void)
{
  GtkWidget *aboutWindow;
  GtkWidget *vbox8;
  GtkWidget *image128;
  GtkWidget *aboutProgramTitleLabel;
  GtkWidget *aboutDescLabel;
  GtkWidget *aboutCopyrightLabel;
  GtkWidget *hbuttonbox1;
  GtkWidget *aboutOKButton;
  GtkWidget *alignment4;
  GtkWidget *hbox8;
  GtkWidget *image127;
  GtkWidget *label10;
  GtkWidget *creditButton;

  aboutWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (aboutWindow, "aboutWindow");
  gtk_window_set_title (GTK_WINDOW (aboutWindow), _("GBabbler About"));
  gtk_window_set_position (GTK_WINDOW (aboutWindow), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (aboutWindow), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (aboutWindow), FALSE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (aboutWindow), TRUE);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox8, "vbox8");
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (aboutWindow), vbox8);

  image128 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image128, "image128");
  gtk_widget_show (image128);
  gtk_box_pack_start (GTK_BOX (vbox8), image128, TRUE, TRUE, 0);

  aboutProgramTitleLabel = gtk_label_new (_(TITLE));
  gtk_widget_set_name (aboutProgramTitleLabel, "aboutProgramTitleLabel");
  gtk_widget_show (aboutProgramTitleLabel);
  gtk_box_pack_start (GTK_BOX (vbox8), aboutProgramTitleLabel, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (aboutProgramTitleLabel), GTK_JUSTIFY_LEFT);

  aboutDescLabel = gtk_label_new (_("Word generator from pools of words !"));
  gtk_widget_set_name (aboutDescLabel, "aboutDescLabel");
  gtk_widget_show (aboutDescLabel);
  gtk_box_pack_start (GTK_BOX (vbox8), aboutDescLabel, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (aboutDescLabel), GTK_JUSTIFY_LEFT);

  aboutCopyrightLabel = gtk_label_new (_("(c) Nicolas Dufour 2003"));
  gtk_widget_set_name (aboutCopyrightLabel, "aboutCopyrightLabel");
  gtk_widget_show (aboutCopyrightLabel);
  gtk_box_pack_start (GTK_BOX (vbox8), aboutCopyrightLabel, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (aboutCopyrightLabel), GTK_JUSTIFY_LEFT);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox1, "hbuttonbox1");
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox8), hbuttonbox1, TRUE, TRUE, 0);

  aboutOKButton = gtk_button_new ();
  gtk_widget_set_name (aboutOKButton, "aboutOKButton");
  gtk_widget_show (aboutOKButton);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), aboutOKButton);
  GTK_WIDGET_SET_FLAGS (aboutOKButton, GTK_CAN_DEFAULT);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment4, "alignment4");
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (aboutOKButton), alignment4);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox8, "hbox8");
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox8);

  image127 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image127, "image127");
  gtk_widget_show (image127);
  gtk_box_pack_start (GTK_BOX (hbox8), image127, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_set_name (label10, "label10");
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox8), label10, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_LEFT);

  creditButton = gtk_button_new_with_mnemonic (_("Credits"));
  gtk_widget_set_name (creditButton, "creditButton");
  gtk_widget_show (creditButton);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), creditButton);
  GTK_WIDGET_SET_FLAGS (creditButton, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) aboutWindow, "destroy",
                    G_CALLBACK (on_aboutWindow_destroy),
                    NULL);
  g_signal_connect_swapped ((gpointer) aboutOKButton, "clicked",
                            G_CALLBACK (on_aboutOKButton_clicked),
                            GTK_OBJECT (aboutWindow));
  g_signal_connect ((gpointer) creditButton, "clicked",
                    G_CALLBACK (on_creditButton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutWindow, aboutWindow, "aboutWindow");
  GLADE_HOOKUP_OBJECT (aboutWindow, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (aboutWindow, image128, "image128");
  GLADE_HOOKUP_OBJECT (aboutWindow, aboutProgramTitleLabel, "aboutProgramTitleLabel");
  GLADE_HOOKUP_OBJECT (aboutWindow, aboutDescLabel, "aboutDescLabel");
  GLADE_HOOKUP_OBJECT (aboutWindow, aboutCopyrightLabel, "aboutCopyrightLabel");
  GLADE_HOOKUP_OBJECT (aboutWindow, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (aboutWindow, aboutOKButton, "aboutOKButton");
  GLADE_HOOKUP_OBJECT (aboutWindow, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (aboutWindow, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (aboutWindow, image127, "image127");
  GLADE_HOOKUP_OBJECT (aboutWindow, label10, "label10");
  GLADE_HOOKUP_OBJECT (aboutWindow, creditButton, "creditButton");

  gtk_widget_grab_focus (aboutOKButton);
  return aboutWindow;
}

GtkWidget*
create_authorWindow (void)
{
  GtkWidget *authorWindow;
  GtkWidget *vbox12;
  GtkWidget *notebook1;
  GtkWidget *label35;
  GtkWidget *label32;
  GtkWidget *hbuttonbox3;
  GtkWidget *authorOKButton;
  GtkWidget *alignment14;
  GtkWidget *hbox26;
  GtkWidget *image195;
  GtkWidget *label34;

  authorWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (authorWindow, "authorWindow");
  gtk_window_set_title (GTK_WINDOW (authorWindow), _("Credits"));
  gtk_window_set_position (GTK_WINDOW (authorWindow), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (authorWindow), TRUE);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox12, "vbox12");
  gtk_widget_show (vbox12);
  gtk_container_add (GTK_CONTAINER (authorWindow), vbox12);

  notebook1 = gtk_notebook_new ();
  gtk_widget_set_name (notebook1, "notebook1");
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox12), notebook1, TRUE, TRUE, 0);

  label35 = gtk_label_new (_("Nicolas Dufour <nicolasdufour@earthlink.net>\nhttp://www.nemoworld.info/\n\nIt was fun to write it ;-)"));
  gtk_widget_set_name (label35, "label35");
  gtk_widget_show (label35);
  gtk_container_add (GTK_CONTAINER (notebook1), label35);
  gtk_label_set_justify (GTK_LABEL (label35), GTK_JUSTIFY_LEFT);

  label32 = gtk_label_new (_("Written by"));
  gtk_widget_set_name (label32, "label32");
  gtk_widget_show (label32);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label32);
  gtk_label_set_justify (GTK_LABEL (label32), GTK_JUSTIFY_LEFT);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox3, "hbuttonbox3");
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (vbox12), hbuttonbox3, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_END);

  authorOKButton = gtk_button_new ();
  gtk_widget_set_name (authorOKButton, "authorOKButton");
  gtk_widget_show (authorOKButton);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), authorOKButton);
  GTK_WIDGET_SET_FLAGS (authorOKButton, GTK_CAN_DEFAULT);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment14, "alignment14");
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (authorOKButton), alignment14);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox26, "hbox26");
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox26);

  image195 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image195, "image195");
  gtk_widget_show (image195);
  gtk_box_pack_start (GTK_BOX (hbox26), image195, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_set_name (label34, "label34");
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox26), label34, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label34), GTK_JUSTIFY_LEFT);

  g_signal_connect ((gpointer) authorWindow, "destroy",
                    G_CALLBACK (on_authorWindow_destroy),
                    NULL);
  g_signal_connect ((gpointer) authorOKButton, "clicked",
                    G_CALLBACK (on_authorOKButton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (authorWindow, authorWindow, "authorWindow");
  GLADE_HOOKUP_OBJECT (authorWindow, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (authorWindow, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (authorWindow, label35, "label35");
  GLADE_HOOKUP_OBJECT (authorWindow, label32, "label32");
  GLADE_HOOKUP_OBJECT (authorWindow, hbuttonbox3, "hbuttonbox3");
  GLADE_HOOKUP_OBJECT (authorWindow, authorOKButton, "authorOKButton");
  GLADE_HOOKUP_OBJECT (authorWindow, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (authorWindow, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (authorWindow, image195, "image195");
  GLADE_HOOKUP_OBJECT (authorWindow, label34, "label34");

  return authorWindow;
}

GtkWidget*
create_fileselection (void)
{
  GtkWidget *fileselection;
  GtkWidget *ok_button1;
  GtkWidget *cancel_button1;

  fileselection = gtk_file_selection_new (_("Choose a theme file"));
  gtk_widget_set_name (fileselection, "fileselection");
  gtk_container_set_border_width (GTK_CONTAINER (fileselection), 10);
  gtk_window_set_position (GTK_WINDOW (fileselection), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (fileselection), TRUE);

  ok_button1 = GTK_FILE_SELECTION (fileselection)->ok_button;
  gtk_widget_set_name (ok_button1, "ok_button1");
  gtk_widget_show (ok_button1);
  GTK_WIDGET_SET_FLAGS (ok_button1, GTK_CAN_DEFAULT);

  cancel_button1 = GTK_FILE_SELECTION (fileselection)->cancel_button;
  gtk_widget_set_name (cancel_button1, "cancel_button1");
  gtk_widget_show (cancel_button1);
  GTK_WIDGET_SET_FLAGS (cancel_button1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) fileselection, "response",
                    G_CALLBACK (on_fileselection_response),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection, fileselection, "fileselection");
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection, ok_button1, "ok_button1");
  GLADE_HOOKUP_OBJECT_NO_REF (fileselection, cancel_button1, "cancel_button1");

  return fileselection;
}

